vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /media/prestations
            upload_destination: '%kernel.project_dir%/public/media/prestations'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true